#!/usr/bin/env python3
"""Sync backend API/WS contracts into frontend generated artifacts."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from starlette.routing import WebSocketRoute

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from sre_agent.models.events import EventType
from sre_agent.server import create_app

DEFAULT_OPENAPI_PATH = REPO_ROOT / "sre_agent" / "frontend" / "src" / "api" / "generated" / "openapi.json"
DEFAULT_TS_PATH = REPO_ROOT / "sre_agent" / "frontend" / "src" / "api" / "generated" / "backend-contract.ts"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate frontend contract artifacts from backend schema.")
    parser.add_argument("--openapi-output", default=str(DEFAULT_OPENAPI_PATH), help="Path to generated OpenAPI JSON.")
    parser.add_argument("--ts-output", default=str(DEFAULT_TS_PATH), help="Path to generated TypeScript contract file.")
    parser.add_argument("--check", action="store_true", help="Check mode: fail if generated content differs from files.")
    return parser


def ensure_auth_env() -> None:
    os.environ.setdefault("JWT_SECRET", "contract-sync-dev-secret")


def build_openapi_schema() -> dict:
    ensure_auth_env()
    app = create_app()
    return app.openapi()


def collect_ws_paths() -> list[str]:
    ensure_auth_env()
    app = create_app()
    paths = sorted(
        route.path
        for route in app.routes
        if isinstance(route, WebSocketRoute)
    )
    return paths


def generate_contract_ts(*, schema: dict, ws_paths: list[str]) -> str:
    http_paths = sorted(schema.get("paths", {}).keys())
    ws_event_types = [member.value for member in EventType]
    lines = [
        "// AUTO-GENERATED by sre_agent/scripts/sync_frontend_contract.py",
        "// Do not edit manually. Run: npm run contract:sync",
        "",
        f'export const CONTRACT_SCHEMA_VERSION = "{schema.get("info", {}).get("version", "unknown")}" as const;',
        "",
        "export const HTTP_PATHS = [",
    ]
    for path in http_paths:
        lines.append(f'  "{path}",')
    lines.extend(
        [
            "] as const;",
            "export type HttpPath = (typeof HTTP_PATHS)[number];",
            "",
            "export const WS_PATHS = [",
        ]
    )
    for path in ws_paths:
        lines.append(f'  "{path}",')
    lines.extend(
        [
            "] as const;",
            "export type WsPath = (typeof WS_PATHS)[number];",
            "",
            "export const WS_EVENT_TYPES = [",
        ]
    )
    for event_type in ws_event_types:
        lines.append(f'  "{event_type}",')
    lines.extend(
        [
            "] as const;",
            "export type WSEventType = (typeof WS_EVENT_TYPES)[number];",
            "",
        ]
    )
    return "\n".join(lines)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def serialize_json(payload: dict) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def main() -> int:
    args = build_parser().parse_args()
    openapi_path = Path(args.openapi_output).expanduser()
    ts_path = Path(args.ts_output).expanduser()

    schema = build_openapi_schema()
    ws_paths = collect_ws_paths()
    contract_ts = generate_contract_ts(schema=schema, ws_paths=ws_paths)
    openapi_text = serialize_json(schema)

    if args.check:
        existing_openapi = openapi_path.read_text(encoding="utf-8") if openapi_path.exists() else ""
        existing_ts = ts_path.read_text(encoding="utf-8") if ts_path.exists() else ""
        expected_ts = contract_ts.rstrip() + "\n"
        if existing_openapi != openapi_text or existing_ts != expected_ts:
            print("[mismatch] frontend contract artifacts are out of date")
            print(f"  - openapi: {openapi_path}")
            print(f"  - typescript: {ts_path}")
            return 1
        print(f"[ok] frontend contract artifacts are up to date: {openapi_path}, {ts_path}")
        return 0

    write_json(openapi_path, schema)
    write_text(ts_path, contract_ts)

    print(f"[ok] wrote OpenAPI schema: {openapi_path}")
    print(f"[ok] wrote TS contract: {ts_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
