#!/usr/bin/env python3
"""Run a real Wave-5 remediation drill and archive API/WS/metrics evidence."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import quote
from uuid import uuid4

import httpx

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from sre_agent.auth.jwt import CurrentUser, encode_token, resolve_jwt_settings

REMEDIATION_TERMINAL_STAGES = {
    "execution_succeeded",
    "execution_failed",
    "execution_timeout",
    "escalation_required",
}
REMEDIATION_KEY_STAGES = {
    "approval_required",
    "plan_revised",
    "approval_accepted",
    "approval_rejected",
    "execution_started",
    "execution_mocked",
    "observation_started",
    "observation_result",
    "execution_succeeded",
    "execution_failed",
    "execution_timeout",
    "escalation_required",
    "rollback_started",
    "rollback_succeeded",
    "rollback_failed",
}


@dataclass(frozen=True)
class DrillSettings:
    base_url: str
    evidence_root: Path
    run_id: str
    user: str
    role: str
    ws_max_events: int
    ws_timeout_seconds: int
    reconnect_attempts: int
    token: str


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a controlled Wave-5 real-environment drill.")
    parser.add_argument("--base-url", default="http://127.0.0.1:8000", help="Backend base URL.")
    parser.add_argument("--evidence-root", default="sre_agent/docs/evidence", help="Evidence root directory.")
    parser.add_argument("--run-id", default="", help="Run id, default: YYYYMMDD-HHMM-wave5-real")
    parser.add_argument("--user", default="wave5-operator", help="Approval user name.")
    parser.add_argument("--role", default="operator", choices=["viewer", "operator", "admin"], help="JWT role.")
    parser.add_argument("--token", default="", help="Bearer token. If empty, generate from local JWT settings.")
    parser.add_argument(
        "--runtime-info",
        default="sre_agent/temp/dev_runtime_info.json",
        help="Runtime info generated by start_frontend_backend.py (for frontend_url/token fallback).",
    )
    parser.add_argument("--frontend-url", default="", help="Frontend URL used in manual acceptance instructions.")
    parser.add_argument("--skip-rollback", action="store_true", help="Skip rollback step during drill.")
    parser.add_argument("--ws-max-events", type=int, default=200, help="Maximum WS events to capture.")
    parser.add_argument("--ws-timeout-seconds", type=int, default=8, help="WS capture timeout in seconds.")
    parser.add_argument("--reconnect-attempts", type=int, default=5, help="WS reconnect checks to run.")
    return parser.parse_args()


def _normalize_base_url(base_url: str) -> str:
    return base_url.rstrip("/")


def _load_runtime_info(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return {}
    return payload if isinstance(payload, dict) else {}


def _build_token(explicit: str, user: str, role: str, runtime_info: dict[str, Any]) -> str:
    if explicit.strip():
        return explicit.strip()
    env_token = os.getenv("SRE_API_TOKEN", "").strip()
    if env_token:
        return env_token
    runtime_token = str(runtime_info.get("frontend_bearer_token", "")).strip()
    if runtime_token:
        return runtime_token
    settings = resolve_jwt_settings()
    current = CurrentUser(user_id=f"wave5-{user}", username=user, role=role)  # type: ignore[arg-type]
    return encode_token(current, settings)


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


def _parse_iso(value: str) -> datetime:
    normalized = value.replace("Z", "+00:00")
    return datetime.fromisoformat(normalized)


def _percentile(values: list[float], q: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    index = int(round((len(ordered) - 1) * q))
    return ordered[max(0, min(index, len(ordered) - 1))]


def _ws_base_from_http(base_url: str) -> str:
    if base_url.startswith("https://"):
        return "wss://" + base_url[len("https://") :]
    if base_url.startswith("http://"):
        return "ws://" + base_url[len("http://") :]
    raise ValueError(f"unsupported base url: {base_url}")


def _ensure_dirs(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    for category in ("api", "ws", "metrics", "ui"):
        (root / category).mkdir(parents=True, exist_ok=True)


def _post_json(
    client: httpx.Client,
    *,
    method: str,
    path: str,
    headers: dict[str, str],
    payload: dict[str, Any] | None,
    exchanges: list[dict[str, Any]],
) -> dict[str, Any]:
    url = f"{client.base_url}{path}"
    started_at = _now_iso()
    response = client.request(method, path, headers=headers, json=payload)
    ended_at = _now_iso()
    body: dict[str, Any]
    try:
        body = response.json()
    except Exception:  # noqa: BLE001
        body = {"raw": response.text}
    exchanges.append(
        {
            "method": method,
            "url": url,
            "request_body": payload,
            "status_code": response.status_code,
            "response_body": body,
            "started_at": started_at,
            "ended_at": ended_at,
        }
    )
    response.raise_for_status()
    return body


async def _capture_ws_events(
    *,
    ws_base: str,
    session_id: str,
    token: str,
    last_event_id: str,
    max_events: int,
    timeout_seconds: int,
) -> dict[str, Any]:
    try:
        import websockets
    except ModuleNotFoundError:
        return {"supported": False, "reason": "python package 'websockets' is not installed", "events": []}

    url = f"{ws_base}/ws/thinking-trace/{quote(session_id)}?token={quote(token)}&last_event_id={quote(last_event_id)}"
    deadline = asyncio.get_running_loop().time() + max(1, timeout_seconds)
    events: list[dict[str, Any]] = []
    try:
        async with websockets.connect(url, open_timeout=5, close_timeout=1) as websocket:
            while len(events) < max_events and asyncio.get_running_loop().time() < deadline:
                remaining = deadline - asyncio.get_running_loop().time()
                if remaining <= 0:
                    break
                try:
                    raw = await asyncio.wait_for(websocket.recv(), timeout=min(1.0, remaining))
                except TimeoutError:
                    break
                payload = json.loads(raw)
                payload["received_at"] = _now_iso()
                events.append(payload)
    except Exception as exc:  # noqa: BLE001
        return {"supported": True, "error": str(exc), "events": events}
    return {"supported": True, "events": events}


async def _run_reconnect_checks(
    *,
    ws_base: str,
    session_id: str,
    token: str,
    checkpoints: list[str],
) -> list[dict[str, Any]]:
    if not checkpoints:
        return []
    try:
        import websockets
    except ModuleNotFoundError:
        return [{"checkpoint": cp, "success": False, "reason": "websockets package missing"} for cp in checkpoints]

    results: list[dict[str, Any]] = []
    for checkpoint in checkpoints:
        url = (
            f"{ws_base}/ws/thinking-trace/{quote(session_id)}"
            f"?token={quote(token)}&last_event_id={quote(checkpoint)}"
        )
        try:
            async with websockets.connect(url, open_timeout=5, close_timeout=1) as websocket:
                raw = await asyncio.wait_for(websocket.recv(), timeout=2.0)
            payload = json.loads(raw)
            next_event_id = str(payload.get("data", {}).get("event_id", ""))
            success = bool(next_event_id) and next_event_id != checkpoint
            results.append(
                {
                    "checkpoint": checkpoint,
                    "success": success,
                    "next_event_id": next_event_id,
                    "received_type": payload.get("type"),
                }
            )
        except Exception as exc:  # noqa: BLE001
            results.append({"checkpoint": checkpoint, "success": False, "reason": str(exc)})
    return results


def _compute_event_missing_rate(event_ids: list[int]) -> tuple[float, int]:
    if len(event_ids) <= 1:
        return 0.0, 0
    ordered = sorted(set(event_ids))
    expected = ordered[-1] - ordered[0] + 1
    missing = max(0, expected - len(ordered))
    if expected <= 0:
        return 0.0, 0
    return missing / expected, missing


def _compute_metrics(events: list[dict[str, Any]], reconnect: list[dict[str, Any]]) -> dict[str, Any]:
    int_event_ids: list[int] = []
    delivery_latencies: list[float] = []
    stages: dict[str, str] = {}
    for event in events:
        event_id = event.get("data", {}).get("event_id")
        if isinstance(event_id, str) and event_id.isdigit():
            int_event_ids.append(int(event_id))
        elif isinstance(event_id, int):
            int_event_ids.append(event_id)

        event_time = event.get("timestamp")
        received_at = event.get("received_at")
        if isinstance(event_time, str) and isinstance(received_at, str):
            try:
                latency = (_parse_iso(received_at) - _parse_iso(event_time)).total_seconds()
                if latency >= 0:
                    delivery_latencies.append(latency)
            except Exception:  # noqa: BLE001
                pass

        if event.get("type") == "remediation_progress":
            stage = event.get("data", {}).get("stage")
            if isinstance(stage, str) and stage not in stages:
                stages[stage] = event.get("timestamp", "")

    missing_rate, missing_count = _compute_event_missing_rate(int_event_ids)
    reconnect_total = len(reconnect)
    reconnect_success = sum(1 for item in reconnect if item.get("success") is True)
    execution_duration = None
    rollback_duration = None
    if "execution_started" in stages and "execution_succeeded" in stages:
        execution_duration = (_parse_iso(stages["execution_succeeded"]) - _parse_iso(stages["execution_started"])).total_seconds()
    if "rollback_started" in stages and "rollback_succeeded" in stages:
        rollback_duration = (_parse_iso(stages["rollback_succeeded"]) - _parse_iso(stages["rollback_started"])).total_seconds()

    return {
        "computed_at": _now_iso(),
        "event_count": len(events),
        "event_id_min": min(int_event_ids) if int_event_ids else None,
        "event_id_max": max(int_event_ids) if int_event_ids else None,
        "event_missing_count": missing_count,
        "event_missing_rate": missing_rate,
        "ws_delivery_seconds_p95": _percentile(delivery_latencies, 0.95),
        "ws_delivery_seconds_samples": delivery_latencies,
        "reconnect_attempts": reconnect_total,
        "reconnect_successes": reconnect_success,
        "reconnect_success_rate": (reconnect_success / reconnect_total) if reconnect_total else None,
        "execution_duration_seconds": execution_duration,
        "rollback_duration_seconds": rollback_duration,
        "stage_timestamps": stages,
    }


def _as_record(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _unwrap_envelope_data(payload: Any) -> Any:
    if not isinstance(payload, dict):
        return None
    if payload.get("success") is not True:
        return None
    return payload.get("data")


def _event_stage(event: dict[str, Any]) -> str:
    event_type = str(event.get("type", "")).strip().lower()
    if event_type != "remediation_progress":
        return event_type
    data = _as_record(event.get("data"))
    stage = str(data.get("stage", "")).strip().lower()
    return stage or "remediation_progress"


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _format_stage_label(stage: str) -> str:
    labels = {
        "approval_required": "等待审批",
        "plan_revised": "方案已修订",
        "approval_accepted": "审批通过",
        "approval_rejected": "审批拒绝",
        "execution_started": "开始执行",
        "execution_mocked": "模拟执行完成",
        "observation_started": "开始观察",
        "observation_result": "观察结果返回",
        "execution_succeeded": "执行成功",
        "execution_failed": "执行失败",
        "execution_timeout": "执行超时",
        "escalation_required": "需要人工介入",
        "rollback_started": "开始回滚",
        "rollback_succeeded": "回滚成功",
        "rollback_failed": "回滚失败",
    }
    return labels.get(stage, stage)


def _build_manual_acceptance_payload(
    *,
    run_id: str,
    base_url: str,
    frontend_url: str,
    session_id: str,
    session_payload: dict[str, Any],
    events_payload: dict[str, Any],
    approve_payload: dict[str, Any],
    rollback_payload: dict[str, Any] | None,
) -> dict[str, Any]:
    session_data = _as_record(_unwrap_envelope_data(session_payload))
    diagnosis_result = _as_record(session_data.get("diagnosis_result"))
    plan = _as_record(diagnosis_result.get("recommended_fix"))
    plan_steps = plan.get("steps")
    if not isinstance(plan_steps, list):
        plan_steps = []

    all_events = _unwrap_envelope_data(events_payload)
    if not isinstance(all_events, list):
        all_events = []
    normalized_events = [item for item in all_events if isinstance(item, dict)]

    timeline_events: list[dict[str, Any]] = []
    ordered_stages: list[str] = []
    for item in normalized_events:
        stage = _event_stage(item)
        if stage not in REMEDIATION_KEY_STAGES:
            continue
        ordered_stages.append(stage)
        data = _as_record(item.get("data"))
        timeline_events.append(
            {
                "timestamp": item.get("timestamp"),
                "event_type": item.get("type"),
                "stage": stage,
                "label": _format_stage_label(stage),
                "message": str(data.get("message", "")).strip(),
                "plan_version": data.get("plan_version"),
            }
        )

    approval_index = next((idx for idx, stage in enumerate(ordered_stages) if stage in {"approval_required", "approval_accepted"}), None)
    execution_index = next((idx for idx, stage in enumerate(ordered_stages) if stage == "execution_started"), None)
    observation_start_index = next((idx for idx, stage in enumerate(ordered_stages) if stage == "observation_started"), None)
    observation_result_index = next((idx for idx, stage in enumerate(ordered_stages) if stage == "observation_result"), None)
    terminal_index = next((idx for idx, stage in enumerate(ordered_stages) if stage in REMEDIATION_TERMINAL_STAGES), None)
    timeline_sequence_ok = all(
        value is not None
        for value in (
            approval_index,
            execution_index,
            observation_start_index,
            observation_result_index,
            terminal_index,
        )
    )
    if timeline_sequence_ok:
        timeline_sequence_ok = bool(
            approval_index <= execution_index <= observation_start_index <= observation_result_index <= terminal_index
        )

    execution_terminal_event = next(
        (item for item in reversed(normalized_events) if _event_stage(item) in REMEDIATION_TERMINAL_STAGES),
        None,
    )
    execution_terminal_data = _as_record(_as_record(execution_terminal_event).get("data"))
    observation_event = next((item for item in reversed(normalized_events) if _event_stage(item) == "observation_result"), None)
    observation_data = _as_record(_as_record(observation_event).get("data"))
    terminal_stage = _event_stage(execution_terminal_event) if execution_terminal_event else ""
    step_results = execution_terminal_data.get("step_results")
    if not isinstance(step_results, list):
        step_results = []
    approve_data = _as_record(_unwrap_envelope_data(approve_payload))
    steps_completed = _safe_int(
        execution_terminal_data.get("steps_completed"),
        _safe_int(approve_data.get("steps_completed"), 0),
    )
    execution_mode = "real"
    if "execution_mocked" in ordered_stages:
        execution_mode = "mock"
    elif any(
        bool(_as_record(item).get("mocked")) or str(_as_record(item).get("command", "")).startswith("mock::")
        for item in step_results
    ):
        execution_mode = "mock"
    alert_cleared = observation_data.get("alert_cleared")
    metrics_improved = observation_data.get("metrics_improved")

    plan_steps_count = len(plan_steps)
    if terminal_stage == "execution_succeeded":
        one_shot_progress = 100
        one_shot_status = "resolved"
    elif terminal_stage == "execution_timeout":
        one_shot_status = "timeout"
        one_shot_progress = 0 if plan_steps_count == 0 else round(max(0, min(steps_completed, plan_steps_count)) / plan_steps_count * 100)
    elif terminal_stage == "escalation_required":
        one_shot_status = "escalated"
        one_shot_progress = 0 if plan_steps_count == 0 else round(max(0, min(steps_completed, plan_steps_count)) / plan_steps_count * 100)
    elif terminal_stage == "execution_failed":
        one_shot_status = "failed"
        one_shot_progress = 0 if plan_steps_count == 0 else round(max(0, min(steps_completed, plan_steps_count)) / plan_steps_count * 100)
    elif "approval_rejected" in ordered_stages:
        one_shot_status = "rejected"
        one_shot_progress = 0
    else:
        one_shot_status = "pending"
        one_shot_progress = 0 if plan_steps_count == 0 else round(max(0, min(steps_completed, plan_steps_count)) / plan_steps_count * 100)

    current_status = str(session_data.get("status", "")).strip().lower()
    has_single_batch_status = one_shot_status in {"pending", "validating", "resolved", "failed", "timeout", "escalated", "rejected"}
    checks = {
        "approve_path_is_real_execution": {
            "passed": execution_mode == "real",
            "detail": f"execution_mode={execution_mode}",
        },
        "execution_steps_has_plan": {
            "passed": plan_steps_count > 0,
            "detail": f"plan_steps={plan_steps_count}",
        },
        "timeline_contains_approval_execution_observation_result": {
            "passed": timeline_sequence_ok,
            "detail": (
                " -> ".join(ordered_stages)
                if ordered_stages
                else "no remediation key events in /api/sessions/{id}/events"
            ),
        },
        "canary_one_shot_projection_ready": {
            "passed": has_single_batch_status,
            "detail": f"batch=一次性执行, progress={one_shot_progress}, status={one_shot_status}, session_status={current_status or 'unknown'}",
        },
    }

    checks["observation_reports_alert_cleared"] = {
        "passed": alert_cleared is True,
        "detail": f"alert_cleared={alert_cleared!r}",
    }
    checks["observation_reports_metrics_improved"] = {
        "passed": metrics_improved is True,
        "detail": f"metrics_improved={metrics_improved!r}",
    }

    missing = []
    if approval_index is None:
        missing.append("approval_required/approval_accepted")
    if execution_index is None:
        missing.append("execution_started")
    if observation_start_index is None:
        missing.append("observation_started")
    if observation_result_index is None:
        missing.append("observation_result")
    if terminal_index is None:
        missing.append("execution_terminal_stage")

    return {
        "generated_at": _now_iso(),
        "run_id": run_id,
        "base_url": base_url,
        "frontend_url": frontend_url,
        "session_id": session_id,
        "session_status": current_status or None,
        "plan": {
            "plan_id": plan.get("plan_id"),
            "priority": plan.get("priority"),
            "confidence": plan.get("confidence"),
            "step_count": plan_steps_count,
            "steps": plan_steps,
        },
        "timeline": {
            "event_count": len(timeline_events),
            "ordered_stages": ordered_stages,
            "key_events": timeline_events,
            "missing_expected_stages": missing,
        },
        "one_shot_projection": {
            "batch": "一次性执行",
            "progress": one_shot_progress,
            "status": one_shot_status,
            "steps_completed": steps_completed,
            "total_steps": plan_steps_count,
            "terminal_stage": terminal_stage or None,
            "step_result_count": len(step_results),
            "execution_mode": execution_mode,
        },
        "observation": {
            "alert_cleared": alert_cleared,
            "metrics_improved": metrics_improved,
            "baseline_alert": observation_data.get("baseline_alert"),
            "post_alert": observation_data.get("post_alert"),
            "alert_review": observation_data.get("alert_review"),
            "metric_reviews": observation_data.get("metric_reviews"),
        },
        "checks": checks,
        "api_boundaries": {
            "used": [
                "/api/diagnose",
                f"/api/remediate/{session_id}/approve",
                f"/api/remediate/{session_id}/rollback",
                f"/api/sessions/{session_id}",
                f"/api/sessions/{session_id}/events",
            ],
            "notes": "Manual remediation-page acceptance should use /remediation/{session_id} and compare with API evidence.",
            "rollback_called": rollback_payload is not None,
        },
    }


def _render_manual_acceptance_markdown(payload: dict[str, Any]) -> str:
    checks = _as_record(payload.get("checks"))
    plan = _as_record(payload.get("plan"))
    timeline = _as_record(payload.get("timeline"))
    one_shot = _as_record(payload.get("one_shot_projection"))
    session_id = str(payload.get("session_id", ""))
    base_url = str(payload.get("base_url", ""))
    frontend_url = str(payload.get("frontend_url", "")).rstrip("/")
    remediation_url = f"{frontend_url}/remediation/{session_id}" if frontend_url and session_id else "/remediation/{session_id}"
    lines = [
        f"# Wave5 修复页手工验收脚本（{payload.get('run_id', '')}）",
        "",
        f"- 生成时间：{payload.get('generated_at', '')}",
        f"- 会话 ID：`{session_id}`",
        f"- 后端地址：`{base_url}`",
        f"- 修复页地址：`{remediation_url}`",
        "",
        "## 自动预检查",
        "",
        "| 检查项 | 结果 | 说明 |",
        "| --- | --- | --- |",
    ]
    for key, item in checks.items():
        detail = _as_record(item)
        passed = bool(detail.get("passed"))
        lines.append(f"| {key} | {'PASS' if passed else 'FAIL'} | {detail.get('detail', '')} |")

    lines.extend(
        [
            "",
            "## 手工验收步骤",
            "",
            "1. 打开修复页并选择会话",
            f"   - 进入 `{remediation_url}`。",
            "   - 确认顶部会话选择器可见，且选中本次会话。",
            "2. 检查“执行步骤”",
            f"   - 预期步骤数：`{plan.get('step_count', 0)}`。",
            "   - 应显示诊断阶段最终审批版本的步骤（不是占位数据）。",
            "3. 检查“修复时间线”",
            "   - 预期包含审批、执行、观察、结果关键节点。",
            f"   - 关键 stage 序列：`{' -> '.join(timeline.get('ordered_stages', []))}`。",
            "   - 若出现 step_results，应能看到每步命令与执行结果。",
            "4. 检查“金丝雀进度”",
            "   - 当前为单次执行模式，仅 1 条批次记录。",
            f"   - 预期：`batch={one_shot.get('batch', '一次性执行')}`，`progress={one_shot.get('progress', 0)}%`，`status={one_shot.get('status', 'pending')}`。",
            "5. 刷新页面后回放",
            "   - 浏览器刷新后重新进入同一会话，确认执行步骤和时间线仍可回放（不依赖内存态）。",
            "",
            "## API 对照命令",
            "",
            "```bash",
            f"curl -H \"Authorization: Bearer <TOKEN>\" \"{base_url}/api/sessions/{session_id}\"",
            f"curl -H \"Authorization: Bearer <TOKEN>\" \"{base_url}/api/sessions/{session_id}/events?limit=500\"",
            "```",
            "",
            "## 证据文件",
            "",
            "- `api/drill_http_exchanges.json`",
            "- `api/drill_summary.json`",
            "- `ws/thinking_trace_events.json`",
            "- `metrics/wave5_drill_metrics.json`",
            "- `ui/remediation_manual_acceptance.json`",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    args = _parse_args()
    runtime_info = _load_runtime_info(Path(args.runtime_info))
    run_id = args.run_id or f"{datetime.now().strftime('%Y%m%d-%H%M')}-wave5-real"
    token = _build_token(args.token, args.user, args.role, runtime_info)
    frontend_url = str(args.frontend_url or runtime_info.get("frontend_url") or "").strip()
    settings = DrillSettings(
        base_url=_normalize_base_url(args.base_url),
        evidence_root=Path(args.evidence_root),
        run_id=run_id,
        user=args.user,
        role=args.role,
        ws_max_events=max(10, args.ws_max_events),
        ws_timeout_seconds=max(2, args.ws_timeout_seconds),
        reconnect_attempts=max(1, args.reconnect_attempts),
        token=token,
    )

    run_dir = settings.evidence_root / settings.run_id
    _ensure_dirs(run_dir)

    headers = {
        "Authorization": f"Bearer {settings.token}",
        "Content-Type": "application/json",
        "x-trace-id": f"wave5-drill-{uuid4().hex}",
    }
    now = _now_iso()
    alert_payload = {
        "alert_name": "Wave5RealDrillSynthetic",
        "severity": "critical",
        "labels": {
            "namespace": "service",
            "service": "sre-agent-drill",
            "node": "wave5-test-node",
        },
        "annotations": {
            "summary": "Wave5 controlled remediation drill",
            "description": "Controlled real-environment drill for approval and rollback evidence",
        },
        "starts_at": now,
        "fingerprint": f"wave5-drill-{uuid4().hex}",
        "status": "firing",
        "source": "wave5-drill",
    }

    exchanges: list[dict[str, Any]] = []
    with httpx.Client(base_url=settings.base_url, timeout=30.0, trust_env=False) as client:
        diagnose = _post_json(
            client,
            method="POST",
            path="/api/diagnose",
            headers=headers,
            payload=alert_payload,
            exchanges=exchanges,
        )
        if not diagnose.get("success"):
            raise RuntimeError(f"/api/diagnose failed: {diagnose}")
        diagnose_data = diagnose.get("data") or {}
        session_id = str(diagnose_data.get("session_id") or "").strip()
        if not session_id:
            raise RuntimeError(f"missing session_id in diagnose response: {diagnose}")

        approve = _post_json(
            client,
            method="POST",
            path=f"/api/remediate/{session_id}/approve",
            headers=headers,
            payload={"approved": True, "user": settings.user},
            exchanges=exchanges,
        )
        rollback: dict[str, Any] | None = None
        if not args.skip_rollback:
            rollback = _post_json(
                client,
                method="POST",
                path=f"/api/remediate/{session_id}/rollback",
                headers=headers,
                payload=None,
                exchanges=exchanges,
            )

        session = _post_json(
            client,
            method="GET",
            path=f"/api/sessions/{session_id}",
            headers=headers,
            payload=None,
            exchanges=exchanges,
        )
        session_events = _post_json(
            client,
            method="GET",
            path=f"/api/sessions/{session_id}/events?limit=500",
            headers=headers,
            payload=None,
            exchanges=exchanges,
        )

    ws_base = _ws_base_from_http(settings.base_url)
    capture = asyncio.run(
        _capture_ws_events(
            ws_base=ws_base,
            session_id=session_id,
            token=settings.token,
            last_event_id="0",
            max_events=settings.ws_max_events,
            timeout_seconds=settings.ws_timeout_seconds,
        )
    )
    events = capture.get("events", []) if isinstance(capture, dict) else []
    checkpoints: list[str] = []
    if events:
        event_ids = [
            str(item.get("data", {}).get("event_id"))
            for item in events
            if item.get("data", {}).get("event_id") is not None
        ]
        event_ids = [item for item in event_ids if item and item != "None"]
        if len(event_ids) > 1:
            step = max(1, (len(event_ids) - 1) // settings.reconnect_attempts)
            checkpoints = event_ids[:-1:step][: settings.reconnect_attempts]
    reconnect = asyncio.run(
        _run_reconnect_checks(
            ws_base=ws_base,
            session_id=session_id,
            token=settings.token,
            checkpoints=checkpoints,
        )
    )
    metrics = _compute_metrics(events, reconnect)

    api_summary = {
        "run_id": settings.run_id,
        "generated_at": _now_iso(),
        "base_url": settings.base_url,
        "frontend_url": frontend_url or None,
        "session_id": session_id,
        "diagnose_success": bool(diagnose.get("success")),
        "approve_success": bool(approve.get("success")),
        "rollback_called": rollback is not None,
        "rollback_success": bool(rollback.get("success")) if rollback is not None else None,
        "capture": capture,
    }
    manual_acceptance_payload = _build_manual_acceptance_payload(
        run_id=settings.run_id,
        base_url=settings.base_url,
        frontend_url=frontend_url,
        session_id=session_id,
        session_payload=session,
        events_payload=session_events,
        approve_payload=approve,
        rollback_payload=rollback,
    )
    api_summary["execution_mode"] = _as_record(manual_acceptance_payload.get("one_shot_projection")).get("execution_mode")
    api_summary["observation"] = manual_acceptance_payload.get("observation")
    manual_acceptance_markdown = _render_manual_acceptance_markdown(manual_acceptance_payload)

    (run_dir / "api" / "drill_http_exchanges.json").write_text(
        json.dumps(exchanges, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (run_dir / "api" / "drill_summary.json").write_text(
        json.dumps(api_summary, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (run_dir / "ws" / "thinking_trace_events.json").write_text(
        json.dumps(events, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (run_dir / "ws" / "reconnect_checks.json").write_text(
        json.dumps(reconnect, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (run_dir / "metrics" / "wave5_drill_metrics.json").write_text(
        json.dumps(metrics, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (run_dir / "ui" / "remediation_manual_acceptance.json").write_text(
        json.dumps(manual_acceptance_payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (run_dir / "ui" / "remediation_manual_acceptance.md").write_text(
        manual_acceptance_markdown,
        encoding="utf-8",
    )

    print(str(run_dir))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
