global:
  aidc_id: local-aidc
  prometheus_url: "http://10.11.4.3:31260"
  alertmanager_url: "http://10.11.4.3:31013/"
knowledge_base:
  persist_dir: ./data/knowledge_db
ontology:
  db_path: ./data/ontology.db
  discovery:
    switches:
      - name: sw-demo
        type: H3C-S9855
        ports:
          - name: HundredGigE1/0/1
            connected_to: node-local-1
