apiVersion: v1
kind: Service
metadata:
  name: sre-agent-web
spec:
  selector:
    app: sre-agent-web
  ports:
    - name: http-frontend
      port: 80
      targetPort: frontend
    - name: http-backend
      port: 8000
      targetPort: backend
